### ISSUE TITLE
As a player, my position at the beginning of the game is randomly chosen from a predefined set of stations.

### ISSUE THREAD

**Issue by Benjay2K** [SE2-GroupProject-Beta/Scotland-Yard-Board-Game#8]
Game Start
As a player, my position at the beginning of the game is randomly chosen from a predefined set of stations.

- [x] Define starting locations for Detectives and Mister X (-> remark from Klemens: a list of possible starting positions is already available in facts_and_figures)
- [x] Randomize starting location

**Comment by Miirym** [comment]
Implemented server side.
